language: java
jdk: oraclejdk8
deploy:
  provider: bintray
  file: bintray.json
  user: ljl
  key:
    secure: QqXfGd7USZ4pmDSa+z5c22JJ4WcVRbYVZJjWZ4Xaqoze02oeOqKUWwlZ7rm40aKCdDOaShmLpG6DCF/o2OVOWaZT3ZYVGcH1xO5q7q0v1Oa6Nm7/bc0ijucNjJtqZjNybKNfXICkxJCC11aGP6NGO2sN++rJNFwSl4EUMvK1R+v7UJAkOc+Wxa6xpQ6jqi3faTkayTpEQPwmzeYHnAs9/U3k++TjcT/DESQjZUckNlA/TD/oJXynAlQtzAT3862z7ZcEZ6gnXglODDNahdr5Sk10h3jZLv7qWxbZVzsfsMwbKlihVX0EtcbUnP8QtxjvTX84Tfvo3rOIQfHck+eDhBPQrBZh+xpzXBDdM3SRRkfeJd4D5B8gCaI8IqPGGDUyr4bUhpGfPT6BC0ArFEWQU49gVO1rfdYloluNMrUA4DtoVryBh6xohHYRFJ05shIYLQYWvW0LileHmOxoY8HmAkiPY11N7VGdrR4R0dGDiEXfUwG1wOd0q8Cp3BUTLKTA24p5rT4RFEOsLuq84nxeLmSHggwcGWkAJGMVhZePrZanyrEaHKJCTieIKD9/KdwGftRlmmy612AqPlealNspY58Xw8uBi5dRp6/EwSw+PNBsHpK2NWcxdaJWQ3SUI7yCnIHfDHOc5moGxxZgJ7ZuGHFIkUDffWS1nyosGh6MC2o=
  dry-run: true
